// <auto-generated />
using System;
using Koncierge.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Koncierge.Domain.Migrations
{
    [DbContext(typeof(KonciergeContext))]
    [Migration("20241005095507_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Koncierge.Domain.Entities.ForwardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RemotePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WithConfigId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WithConfigId");

                    b.ToTable("Forwards");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KubeConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KubeConfigs");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.LinkedConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForwardEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ForwardEntityId");

                    b.ToTable("LinkedConfigs");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.ForwardEntity", b =>
                {
                    b.HasOne("Koncierge.Domain.Entities.KubeConfigEntity", "WithConfig")
                        .WithMany("HasForwards")
                        .HasForeignKey("WithConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WithConfig");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.LinkedConfig", b =>
                {
                    b.HasOne("Koncierge.Domain.Entities.ForwardEntity", null)
                        .WithMany("Configs")
                        .HasForeignKey("ForwardEntityId");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.ForwardEntity", b =>
                {
                    b.Navigation("Configs");
                });

            modelBuilder.Entity("Koncierge.Domain.Entities.KubeConfigEntity", b =>
                {
                    b.Navigation("HasForwards");
                });
#pragma warning restore 612, 618
        }
    }
}
