name: Auto Tag

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitHub Semver Bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch # or minor/major
          WITH_V: true
